# Generated by Django 5.0.1 on 2024-06-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_created_at_order_updated_at_review_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserQuestion',
        ),
    ]
